import re

# Texto extraído del archivo
texto = """Z
O
D
I
AC
OLA LETRA “T” INDICA TERMINACIONES. / LOS BILLETES DE ESTE SORTEO PRESCRIBEN A LOS 60 DIAS NATURALES. 
PARA CONSULTA DE PREMIOS POR VIA TELEFONICA EN LA CIUDAD DE MEXICO Y DE PROVINCIA, MARQUE EL TELEFONO: 55477-00100 OPCION 1 U OPCION 3 DEL MENU O 
INGRESE A NUESTRA PAGINA: www.lotenal.gob.mx 
PARA LOCALIZAR EL NUMERO DE SU SUERTE O INFORMACION GENERAL DE LA LOTERIA NACIONAL, MARQUE  EL TELEFONO: 55514-07000 O ACUDIR A:  PLAZA DE LA 
REFORMA No. 1, C. P. 06037 CIUDAD DE MEXICO. 
AL EFECTUARSE EL PAGO DE LOS BILLETES PREMIADOS SE RETENDRAN LOS IMPUESTOS DE ACUERDO A LAS LEYES VIGENTES DE LA MATERIA. / LOS REINTEGROS NO CAUSAN IMPUESTO.
DIRECTORA GENERAL: LIC. MARGARITA GONZALEZ SARAVIA CALDERON. / REPRESENTANTE DE LA SECRETARIA DE GOBERNACION: LIC. HUMBERTO GONZALEZ SANTOS.
SORTEO ZODIACO 1613 CELEBRADO A LAS 20:00 HRS. EL DOMINGO 14 DE MAYO DE 2023, EN LA CIUDAD DE MEXICO.1613 9
VIRGO ARIES 
0049   t2,200.00 
0149   t2,200.00 
0245   .4,400.00
0249   t2,200.00 
0349   t2,200.00 
0449   t2,200.00 
0549   t2,200.00"""

# Expresión regular para buscar números de 4 dígitos
numeros = re.findall(r'\b\d{4}\b', texto)

# Asignar números a la categoría "aire"
aire = {"números": numeros}

# Imprimir el resultado
print("Números asignados a 'aire':", aire)